config:
	git config --global credential.helper store	

clone:
	git clone https://swasin185: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@github.com/swasin185/$p
	
pull:
	git -C $p pull -v
	
push:
	git -C $p add . 
	git -C $p commit -m "x$2"
	git -C $p push -v
